### ISSUE TITLE
vaadin-button onclick or on-click not working with #valo branch

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-themes#17]
vaadin-button `onclick` or `on-click` not working with `#valo` branch theme.

In `demo/valo/buttons.html` try adding `<vaadin-button onclick="console.log('hello');">Normal</vaadin-button>` and it does not work. Works fine when no valo theme loaded.

**Comment by jouni** [comment]
Let’s see if the changes I’ve made to the button theme affect this. I’ll let you know when I’ve pushed the changes.

**Comment by jouni** [comment]
Actually, I already tried it out and it’s fixed. Not exactly sure what the fix is, though.

**Comment by jouni** [comment]
Keeping this issue open until we verify it works in the bakery app.

**Comment by samiheikki** [comment]
Great!

**Comment by jouni** [comment]
Should be fixed now.
