### ISSUE TITLE
Material theme for vaadin-date-picker

### ISSUE THREAD

**Issue by andreabioli** [vaadin/vaadin-themes#26]
I don't know if I'm using it correctly (never seen before 'theme-for', for example), but if I try to use it 'normally' in the page where I'm using the underlying component, as in:

```
<dom-module id="some-component">
    <template>
        <style include="material-date-picker">

```

then the setting:

```
:host {
        width: 160px;

```
makes the container component obviously 160px wide, that's surely NOT the intended use...
I'm surely missing something, here...

**Comment by H3dz** [comment]
I agree that it's hard to find an example on how to use the themes.

Turns out, it's really simple and all you have to do is include the theme component, no need to add it to style include.

```
<link rel="import" href="../bower_components/vaadin-date-picker/vaadin-date-picker.html">
<link rel="import" href="../bower_components/vaadin-themes/material/vaadin-date-picker.html">
```

**Comment by andreabioli** [comment]
???
Yes, I'm talking just about that! After including them, I have the problem I describe... :-)

**Comment by jouni** [comment]
Hi @andreabioli! What is it that you are trying to do? Make the <vaadin-date-picker> element 160px wide? You should be able to do that just with 

```html
<style>
vaadin-date-picker {
  width: 160px;
}
</style>
```

No need to use `:host` for that. The style modules with `theme-for` attribute are only for providing themes for the elements, and doing some more advanced customizations. Simple customizations should be done with regular CSS.

**Comment by jouni** [comment]
@H3dz 
> Turns out, it's really simple and all you have to do is include the theme component, no need to add it to style include.

One small correction to that: you should import the theme before the element, otherwise the theme won’t be picked up in all browsers (can’t remember was it polyfilled browsers or the other way around).

So the correct order is:

```html
<link rel="import" href="../bower_components/vaadin-themes/material/vaadin-date-picker.html">
<link rel="import" href="../bower_components/vaadin-date-picker/vaadin-date-picker.html">
```

**Comment by jouni** [comment]
Closing as invalid. If you have further questions, please add comments here of in our Gitter chat.
