### ISSUE TITLE
valo-button theme: Bad colors in Edge

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-themes#28]
In Edge button colors for certain demos are not displayed correctly.
See differences Edge vs Chrome
![screen shot 2017-07-24 at 11 02 21](https://user-images.githubusercontent.com/161853/28515963-d1b5a376-705f-11e7-8788-4eb96440c213.png)
![screen shot 2017-07-24 at 11 01 48](https://user-images.githubusercontent.com/161853/28515962-d1b4ac3c-705f-11e7-8d20-a72e3072bef2.png)

**Comment by H3dz** [comment]
I had a similar issue when using the vaadin-themes/material/vaadin-date-picker.html with vaadin-date-picker 2.0.0-beta2 on Edge.

![image](https://user-images.githubusercontent.com/21203225/28632462-a1c30b7c-71fe-11e7-9b33-056f0b5b08de.png)

**Comment by jouni** [comment]
This issue was moved to vaadin/vaadin-valo-theme#4
