### ISSUE TITLE
Initial Valo theme for <vaadin-grid>

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-themes#42]
Specs from https://app.zeplin.io/project/5937d86d3601d452f1b8e66a

Note that styling the checkbox is not part of this task!

**Comment by jouni** [comment]
Is #37 a duplicate?

**Comment by tomivirkki** [comment]
This is a ticket for the initial version where we work with what we have. We still need designs for dark theme, column reordering appearance, frozen columns appearance...
