### ISSUE TITLE
How to style icons?

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-themes#47]
The current way for our elements to define the icons is using custom web fonts, so they can be changed easily with CSS. But it has some drawbacks:
- The need to produce custom web fonts when you want to change the icons in your app/theme
- The rendering of the icons is subject to the font rendering algorithm of the platform, which makes the icons look suboptimal in some situations (like on Windows with ClearType)

I’ve been thinking if we could change the icons to use `iron-icon` instead, which is the standard way of using icons in Polymer apps. So, for `vaadin-date-picker` for example, we would have something like this:

```css
:host {
  --toggle-button-icon: "vaadin:calendar";
}
```

```html
<iron-icon class="toggle-button" icon="[[_getIcon]]"></iron-icon>
```

```javascript
_getIcon() {
  return getComputedStyle(this).getPropertyValue("--toggle-button-icon");
}
```

This wouldn’t allow the developer to dynamically change the icon at runtime (unless we provide some API for that), but I consider that as an acceptable tradeoff, as it’s not a common use case.

Thoughts, could this work?

**Comment by web-padawan** [comment]
Created a [JSBin](http://jsbin.com/sifojop/edit?html,console,output). Seems to work although requires additional code for IE and deferring until `isAttached` (setting some property in `ready`callback and passing it as a parameter to computed binding works too).

FYI, `iron-icon` currently pulls in `iron-flex-layout` and all of those style mixins which might be irrelevant for Vaadin elements, as I guess.

**Comment by jouni** [comment]
So technically it seems viable. What’s your opinion, would this be a better alternative than web fonts?

The drawback with iron-icon is of course that you need to produce a new `iron-iconset-svg` element that contains the icons (if you want to use icons which are not available in Material/Vaadin/Valo icons), so it’s not the easiest way for a designer either.

Another option, which would be more straightforward for a designer, would perhaps be to let the developer provide a URL for an SVG file, in CSS, which we could fetch and render as inline SVG then (since the icon should be inline so CSS can target it).

```css
vaadin-date-picker {
  --toggle-button-icon: url("custom-calendar-icon.svg");
}
```

**Comment by jouni** [comment]
I suppose, technically, we could support both, as we could detect from the property value if it’s pointing to a URL or to an icon name.

**Comment by web-padawan** [comment]
Here is another [JSBin](http://jsbin.com/noloqez/edit?html,console,output) demonstrating the icon detection principle mentioned above. Works as well but might require some styling tricks to prevent flash of loading icon (at least noticeable in IE even for local environment).

**Comment by jouni** [comment]
Great! I’m starting to like where this is going. @tomivirkki, do you spot any problems, other than causing breaking changes to existing themes?

**Comment by tomivirkki** [comment]
Sounds pretty good. But it would also be a breaking change for our components? And depending on iron-icon will add transitive dependencies to Polymer legacy stuff.

**Comment by web-padawan** [comment]
Yes, the tradeoff is that `iron-icon` and `iron-iconset-svg` both rely on legacy stuff including `iron-meta`. I'll continue my investigation to find better solution.

**Comment by jouni** [comment]
Time to put the `<vaadin-icon>` in [vaadin-icons](https://github.com/vaadin/vaadin-icons)? 😅

**Comment by jouni** [comment]
This issue was moved to vaadin/vaadin-core#129
