### ISSUE TITLE
Valo and Material form layout

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-themes#5]
The things a theme can control in a form:

- The gap between the label and the field, when the label is on the side of the field
- The font styles of the form item label, including text alignment (left/right)

The gaps can be controlled with CSS custom properties.

I’m not 100% sure about the approach for the label, as it’s going to be slotted content. Should we target them with `::slotted(*)` and apply correct font styles?

The default gap between columns should be 32px, and the default gap between the label and the field should be 16px.

**Comment by platosha** [comment]
Usually fonts are inherited. We can set label styles on the label slot wrapper, in the shadow DOM of the form item then.

**Comment by jouni** [comment]
This issue was moved to vaadin/vaadin-material-theme#6
